### ISSUE TITLE
Mixtape

### ISSUE THREAD

**Issue by crockpoot** [johanneszab/TumblThree#196] opened 2018-01-11 03:22 UTC
Any chance a mixtape.moe ripper can be implemented alongside the gfycat and webmshare externals?

**Comment by johanneszab** [comment] 2018-01-11 06:16
Duplicate of #183.

**Comment by johanneszab** [comment] 2018-01-11 06:17
I don't have much time for programming TumblThree right now, thus if someone wants to implement this, it could be done similar to the aforementioned gfycat or webmshare implementation.

**Comment by crockpoot** [comment] 2018-01-11 23:05
Ah, my bad. Should have searched first.

**Comment by bun-dev** [comment] 2018-01-12 05:02
I attempted to add mixtape, and so far it works for me. Here is the pull request:
https://github.com/johanneszab/TumblThree/pull/197

**Comment by johanneszab** [comment] 2018-01-12 07:43
Thanks a lot!

I'll take a look at it at the weekend since there are so many file changes it's hard to see it for me on github alone. I guess most of them is just automatic reformatting.

If you have any ideas of how to better structure the code for newcomers to make it easier to get into it, next to the obviously missing documentation, let me know.

**Comment by crockpoot** [comment] 2018-01-12 23:25
Props to bun-dev~

**Comment by bun-dev** [comment] 2018-01-13 03:21
Yeah, Sorry about that. I forgot to disable it.90% of those changes is from ReSharper code cleanup. For the most part, it's just explicit type changes and using C# 6.0 features when necessary,

As far as making the code better for newcomers,  I'm not really sure yet since I haven't looked at everything. The only thing that is time consuming is plugging everything in for the GUI.

**Comment by johanneszab** [comment] 2018-02-24 10:17
Thanks @bun-dev.

I'll close this now since I've finally had time to merge your code. I've also unified the look a bit and ported things over the hidden Tumblr blog crawler.

**Closed by johanneszab** 2018-02-24 10:17 UTC
Labels: enhancement, help wanted
