### ISSUE TITLE
Is Mac currently supported? Are themes currently supported?

### ISSUE THREAD

**Issue by humanitiesclinic** [johanneszab/TumblThree#333] opened 2018-12-10 18:23 UTC
Can this program be run on a Mac? I saw #176 but wasn't sure of what it meant as I am not a Windows developer. It looked like there was a request for support, but the program is still unable to run on Mac, am I correct?

Also, how about themes? I saw #34.  But am not sure in the end if someone did anything to implement support for themes.

**Comment by johanneszab** [comment] 2018-12-10 18:38
Both no.

Themes in this cases means themes for TumblThree, not downloading a Tumblr blog theme. But there is an open ticket for that as well at #296.

**Comment by johanneszab** [comment] 2018-12-10 19:14
But maybe you give https://github.com/bbolli/tumblr-utils or https://github.com/RipMeApp/ripme a try. They both should work on a Mac. I don't know about the themes thing though, but based on the programming language they are written in, they should run on a Mac.

**Comment by humanitiesclinic** [comment] 2018-12-10 19:36
I ask this question because I had a go with  https://github.com/bbolli/tumblr-utils even before you mentioned it, but although it downloads content, the downloads don't mirror the original skin,look and feel of the site. It's because of this that I decided to try to find alternatives, and chanced upon your project.

"Themes in this cases means themes for TumblThree, not downloading a Tumblr blog theme."
Not very sure what this means. So, if I use TumblThree (instead of https://github.com/bbolli/tumblr-utils) can I get the original skin/feel of the site I wish to download?

**Comment by johanneszab** [comment] 2018-12-25 08:51
Duplicate of #176 and #296.

**Closed by johanneszab** 2018-12-25 08:51 UTC
