### ISSUE TITLE
CommandLine support

### ISSUE THREAD

**Issue by bun-dev** [johanneszab/TumblThree#195] opened 2018-01-10 22:11 UTC
Hello!
Is it possible to have this run arguments from the command line silently?
IE, tumblthree -crawl -all
That would call crawl on all blogs and run in the background(no gui).

The main reason I'd like this is so I can make a simple batch script that crawls my tumblr blogs every 3 days or so, like a subscription. Thanks!

**Comment by johanneszab** [comment] 2018-01-11 06:28
Duplicate of #159.

**Closed** 2018-03-02 09:23 UTC
Labels: enhancement, help wanted
