### ISSUE TITLE
In master, liked-by videos are not downloaded

### ISSUE THREAD

**Issue by throwaway152** [johanneszab/TumblThree#320] opened 2018-12-08 09:04 UTC
I want to download all my tumblr likes and followed the steps. Some images are downloaded but the videos are all duplicates. Either the thumbnails of the video is downloaded or nothing at all. Also, when I download the likes on my own blog, the progress bar doesn't move.

I looked at another thread and I used this tumblr to check it out and it has the same issue.
https://www.tumblr.com/liked/by/lostinadarkdream
Not sure why this is happening. If I just download a tumblr blog, then all the videos are downloaded and it works correctly.

![ss 2018-12-08 at 04 00 06](https://user-images.githubusercontent.com/45709341/49684156-daa73200-fa9d-11e8-875c-931b7ae22e7d.png)

![image](https://user-images.githubusercontent.com/45709341/49684178-41c4e680-fa9e-11e8-958c-86092becb195.png)

**Comment by johanneszab** [comment] 2018-12-08 09:19
Use the 1.0.8.63 version. Seems like a regression from the refactoring.

**Comment by cinoh2000** [comment] 2018-12-09 16:42
Not sure if this is helpful, but what seems to be happening is that it thinks every video is named https://vtt.tumblr.com/.mp4 so it creates one zero-length file called .mp4 in the output directory, and after that, every other video it encounters is a "duplicate."

**Comment by johanneszab** [comment] 2018-12-09 16:45
Should be fixed already in the v1.0.8.65.

**Comment by johanneszab** [comment] 2018-12-11 03:18
@throwaway152:

Sorry for this major fuckup. I actually never wanted to code again when not having time for it. I actually fixed the detection, but forgot to add it to the liked by crawler.

I've liked some random non-NSFW examples and at least now with the v1.0.8.67 those get detected:
https://www.tumblr.com/liked/by/privtumbl

**Closed** 2018-12-24 10:18 UTC
Labels: bug, enhancement, help wanted
