### ISSUE TITLE
Some bugs in the version 1.0.8.18

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#132] opened 2017-08-31 13:07 UTC
1) I often observe this issue that the tag and search pages get stuck in the queue panel and the program only shows either "downloading tumblr_something.jpg" or "calculating unique images, removing duplicates" and nothing else, it can last for hours and nothing happens at the same time. Apparently, such a bug occurs when the download process is nearing the end, and then these pages get stuck in the queue panel. I also noticed that after I pressed the stop button, dozens of files are created immediately and it seems that they were already downloaded because my Internet is not so fast to download files at such a speed.
2) I also noticed that when after first download I re-add the search and tag pages to the queue panel and start downloading again, then during the downloading process many more files are downloaded. It seems that for the first time the program skips some files and then these files are downloaded only if re-add these pages to the queue panel and start the download several times. For example, if add the tag page that contains 20000 images, then the first time the program downloads 15000 images, and the second time 4000 images, and the third time 500 images and so on until this page is maximally downloaded.

Just in case, if you want to check this, here is the list of relatively small pages, containing thousands of files:
https://www.tumblr.com/tagged/sunny-leone
https://www.tumblr.com/tagged/eugenia-diordiychuk
https://www.tumblr.com/tagged/kyla-cole
https://www.tumblr.com/tagged/lorena-b
P.S. Despite these bugs, I am very satisfied with these new features, I downloaded a lot of good content about what I could not have dreamed of before. Thank you for your wonderful work!

**Comment by johanneszab** [comment] 2017-08-31 13:51
2. I'm not sure if that's a bug though. The download code is the same as for the regular blogs and it doesn't happen there. Since I don't know how the search works, It's certainly possible that the returned images/post change at different searches? Maybe some people posted new posts? Why do you think it's bug? Have you set the time span in the tag search at a fixed date? Did you check in your browser that the images are always the same in each corresponding search?

1. You've already [opened an issue](https://github.com/johanneszab/TumblThree/issues/116) about this. I think it's the same thing. I don't have time right now to do the necessary changes as it requires more work and is a fundamental part of the application, I probably won't change it any time soon.

**Comment by Taranchuk** [comment] 2017-09-01 08:17
> Maybe some people posted new posts?

Yes, it is quite possible. Tags that I download are popular and many people post images on them.

> Did you check in your browser that the images are always the same in each corresponding search?

I did not quite understand what this means. if it's about whether new images are added to the search and tag pages after start the crawling, then most likely yes

> Have you set the time span in the tag search at a fixed date? 

No, I did not set the time span. Now put the date 20170830 in the section "To", the section "From" leave blank and start downloading and this time the bug was repeated again, after downloading on two pages in the panel the program shows the message "calculating unique images, removing duplicates" and it already lasts for an hour. So it did not help.

> You've already opened an issue about this. I think it's the same thing. I don't have time right now to do the necessary changes as it requires more work and is a fundamental part of the application, I probably won't change it any time soon.

For me, it's not difficult to add pages to the queue panel several times, anyway I will need to download new posts from time to time and at the same time the program will download missed posts so this is not a problem for me. Here's the fact that the pages get stuck and do not free up space for the next pages, for me personally this is a problem, I have to look at the program every time, checking whether the pages are downloading now or not, and if the download stops, I have to manually press the stop button and delete the stuck pages from the queue panel so that the following pages could start downloading. 

When only a few pages need to be downloaded, this is a small inconvenience, but when several dozen pages need to be downloaded, then it is already becoming a routine. this is not to say that I will need to regularly update the downloaded pages from time to time to download new images so I will have to meet with this bug again and again. :(

**Comment by johanneszab** [comment] 2017-09-02 07:30
Duplicate of #116.

**Closed by johanneszab** 2017-09-02 07:30 UTC

**Comment by Taranchuk** [comment] 2017-09-02 08:01
> Duplicate of #116.

Different issues, I do not think they are duplicates. This topic is about incomplete files when the Internet disappears and about that the function of checking directories does not work for large folders, not about the missed files during downloading and not about that pages get stuck at the end of the download. Although of course you can close this topic, if you want.

**Comment by johanneszab** [comment] 2017-09-03 08:05
> Different issues, I do not think they are duplicates. [..] Although of course you can close this topic, if you want.

...

So, you want to tell me how my application works? I think you don't even understand what I'm saying if I read your [first comment](https://github.com/johanneszab/TumblThree/issues/132#issuecomment-326519909).

I am sure that the crawling never finishes because of your crappy internet connection. And that is exactly the problem in #116. I've already explained you this in that exact issue. I've actually even downloaded 3 of your above mentioned searches and it works without any problems. Thus, the only bug here is your internet connection.

And I don't see any reason why the search code should be wrong. It just RegExes the whole page and continues to the next link in each page. Thus, there is basically nothing that can be wrong. But of course, you probably know that better than me.

**Comment by Taranchuk** [comment] 2017-09-03 12:13
Johannes, I did not mean to offend you or doubt your knowledge. If this seemed to you, then I'm very sorry for that, but I really did not mean it. You are a developer and you know better than me, this is without a doubt. My apologies. Perhaps you are right and the reason in my internet connection. Then we will not talk about this issue anymore.

**Comment by Taranchuk** [comment] 2017-09-03 15:47
It seems I found a solution to how to get rid of the bug. To do this, need to reduce the number of parallel connections. Previously there were 25 parallel connections by default, now I changed this value to 2. After that, I did not notice that the pages got stuck in the queue panel, 7 pages already successfully passed through the queue panel and 15,000+ images were downloaded. Previously, every second page was stuck and more than 5000 images I could not download without manually stopping and restarting the download. For me it's a great relief that this bug is finally gone. I share this information because perhaps it will help someone who has the same bug.

**Comment by Taranchuk** [comment] 2017-09-25 14:20
Today I have updated to the new version and it seems that the bug with stuck in the queue panel is fixed. Previously, I had 25 parallel connections in the settings and no download process could do without this bug, only reducing the value to 2 helped. And now I changed the number of parallel connections to 25 again and now there is no this bug completely, all 5 hours of downloading images by tag and search keywords passed smoothly and without incident. Great, thank you very much for the work!
