### ISSUE TITLE
download liked posts fewer than actually

### ISSUE THREAD

**Issue by hackedbyxx** [johanneszab/TumblThree#177] opened 2017-11-25 12:17 UTC
i liked 1500 more but i can just download 100 or could give me an api of liked posts

**Comment by johanneszab** [comment] 2017-11-25 12:39
1. Without the url/blog you're trying to download, there is no possible fix and no help! Thus, your whole issue creation renders meaningless. Always attach a reproducible step-by-step instruction with your issue reports. How exactly do you except help if I cannot look into the issue? 
2. Are you using the latest version (v1.0.8.32), since there were some considerably changes made in the code?

**Comment by johanneszab** [comment] 2017-11-29 19:58
I've tested 3 liked/by accounts and all photo and video posts were successfully downloaded. Together with the one sentence issue description and the lack of any response, I'm closing this issue.

**Closed by johanneszab** 2017-11-29 19:58 UTC
