### ISSUE TITLE
Cannot add blog

### ISSUE THREAD

**Issue by godlydevils** [johanneszab/TumblThree#35] opened 2017-03-07 01:44 UTC
http://iglovequotes.net/

Although it's tumblr blog, I cannot add it

**Comment by Taranchuk** [comment] 2017-03-07 02:37
Try it
http://iglovequotes.tumblr.com
Also look at this comment from amigre38, it describes how to solve problems with not-tumblr web-address blogs.
https://github.com/johanneszab/TumblThree/issues/21

**Comment by johanneszab** [comment] 2017-03-07 06:57
Duplicate of #21.

**Closed by johanneszab** 2017-03-07 06:57 UTC
Labels: duplicate, enhancement
