### ISSUE TITLE
[BUG] KERNELBASE.dll error 

### ISSUE THREAD

**Issue by magichaotu** [johanneszab/TumblThree#164] opened 2017-10-17 23:14 UTC
When I use TumblThree to start the crawling with three blogs parallelly ，
After a few minutes running, the program shut down and I check the system log:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-10-17T22:57:07.061249500Z" /> 
  <EventRecordID>11114</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>MSI</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>TumblThree.exe</Data> 
  <Data>1.0.8.27</Data> 
  <Data>59e109aa</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.15063.674</Data> 
  <Data>93d2100b</Data> 
  <Data>e0434352</Data> 
  <Data>0000000000069e08</Data> 
  <Data>ac8</Data> 
  <Data>01d3479ab1a6aebe</Data> 
  <Data>D:\TumblThree\TumblThree.exe</Data> 
  <Data>C:\Windows\System32\KERNELBASE.dll</Data> 
  <Data>8b423393-7896-4d5d-a3e4-4ee818975172</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
 
win 10 (1703 / 15063.674 )and .net 4.7

**Comment by johanneszab** [comment] 2017-10-18 03:20
Sadly, that information is useless. You need to paste everything, not just the top of the stack trace, otherwise I cannot help. Please, state the three blogs here as well, so that someone can reproduce the issue and also try and check if that happens only for those 3 blogs or for three different other blogs as well.

Otherwise I'll close the issue, since KERNELBASE.dll is a microsoft .dll. Doesn't mean anything, but with the current information available, there is no issue in TumblThree, and no help possible.

**Closed** 2017-10-26 05:45 UTC
