### ISSUE TITLE
With v1.0.4.19 version the program skipped about one-third percent of meta-data and most of the images

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#27] opened 2017-02-27 18:24 UTC
Hi everyone.
The program does not download some percent of metadata. Here is a screenshot that shows the downloaded blogs in mode downloading only metadata without images
http://i.imgur.com/2fUGxj8.jpg
I also noticed that in the metadata (images.txt) there are many duplicates, whole parts of the text are repeated along the entire file. If remove the duplicates from text, it turns out that the program has downloaded much less metadata.
Cases with the downloaded images are worse, the program does not download a lot of images
For example, there is a blog, sorry it is NSFW
http://sagarxx.tumblr.com
I downloaded this blog twice using TumblThree and another downloader and compared the downloaded folder from two programs. Another downloader has downloaded 1247 images, TumblThree has downloaded only 123 images. And it's not duplicates, I see in the folder from another downloader such an images, which are absent in the Tumblthree folder. Tomorrow I will try to download the same blogs, which I had previously downloaded and see how many images will be downloaded and compared to the number of images that are in the old folders.
This is all what I faced today. Is there anyone who has faced the same problems?
P.S. English is not my native language, so sorry for possible mistakes in the text.

**Comment by johanneszab** [comment] 2017-02-27 18:53
Duplicate of #26 

Please, don't open new bugs for the same issue. It's obvious that you hit the rate limit. Either lower the connections or wait for a proper fix.

**Closed by johanneszab** 2017-02-27 18:53 UTC
Labels: duplicate
