### ISSUE TITLE
Sideblogs are shown as offline

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#102] opened 2017-06-28 05:47 UTC
I tried to authorize, restart the program, they are still shown as offline. Is not there a specific bug on my side, or maybe there's just no support for the sideblogs in the program? 
Here are two such blogs, for example (sorry, they are NSFW):
https://www.tumblr.com/dashboard/blog/hot-fantasies
https://www.tumblr.com/dashboard/blog/robstoughts
Or
http://robstoughts.tumblr.com
http://hot-fantasies.tumblr.com

**Comment by johanneszab** [comment] 2017-06-28 06:15
Duplicate of #4.

**Closed by johanneszab** 2017-06-28 06:15 UTC
