### ISSUE TITLE
Liked/by problem

### ISSUE THREAD

**Issue by alko1234** [johanneszab/TumblThree#171] opened 2017-11-15 18:51 UTC
Hello, I've tried to download my liked/by posts but every attempt gives me error "You need to login to tumblr.com for downloading .... Go to the settings->authenticate. I've tried on two accounts, how to solve this problem?

**Comment by johanneszab** [comment] 2017-11-15 19:32
And what exactly is the error you're getting when you're trying to login? You left the most important part out.

The window that opens is a normal web browser, no TumblThree code. I've just tested it here, the login still works. Thus, I'm quite sure it's not a TumblThree issue at all, but maybe a server issue, or you simply typed in the wrong password. Just try again later, or state the exact error/your problem.

**Comment by johanneszab** [comment] 2017-11-15 19:34
possible duplicate of #83

**Comment by alko1234** [comment] 2017-11-15 19:40
I'm logging in, everything is okay but when I add blog to queue, click "crawl"  i've got error "You need to login to tumblr.com for downloading .... Go to the settings->authenticate" and nothing works, i've tried logging in many times but still it doesn't work, I'm adding a photo of this problem 
![1](https://user-images.githubusercontent.com/33699847/32856453-308f588a-ca45-11e7-98f0-ff9ba51b6c0c.png)
![2](https://user-images.githubusercontent.com/33699847/32856455-30cca406-ca45-11e7-8ce2-72ce82f2e468.jpg)

**Comment by johanneszab** [comment] 2017-11-15 20:04
Can you download these likes after logging in?

http://wallpaperfx.tumblr.com/liked/by/

If yes, then maybe you'll have to temporarily change the visibility/privacy settings of your likes for the download. Somewhere in the settings of you blog at tumblr.com.

**Comment by alko1234** [comment] 2017-11-15 20:16
![image](https://user-images.githubusercontent.com/33699847/32857992-2a99aa2a-ca4a-11e7-94ee-a3ee91892455.png)
I logging in but still get this error

**Comment by johanneszab** [comment] 2017-11-15 20:52
Okay, thanks!

Looks like I broke the cookie handling in the refactoring. Try version v1.0.8.29, that should work. At least for me here with the blog in your screenshot.

**Comment by alko1234** [comment] 2017-11-15 21:04
I'm using version called "TumblThree-v1.0.8.29-Application"

**Comment by johanneszab** [comment] 2017-11-15 21:12
I don't know, works for me. Just not in the beta/pre-release I was posting in #169. That why I commented that.

![tumblthree_liked_by_downloading](https://user-images.githubusercontent.com/1684561/32860418-d6ed6968-ca51-11e7-9c93-43b5528b232e.png)

**Comment by alko1234** [comment] 2017-11-15 21:15
Okay, so thanks a lot for your help! I will try on other computer 👍

**Comment by alko1234** [comment] 2017-11-16 17:15
I've found solution for my problem, I don't know why but when I create new admin account on my computer, and try again download likes it finally works, but I've got another question, on tumblr account I'be got 23k likes but on TumblrThree shows only 10k (with duplicates), is it normal?

**Comment by johanneszab** [comment] 2017-11-16 17:24
The web browser that opens when you click on the _Authenticate_-button is a internet explorer and the cookie is saved it's cache structure. Maybe there is some issue there with your account.

> I've got another question, on tumblr account I'be got 23k likes but on TumblrThree shows only 10k (with duplicates), is it normal?

I've tested it on 2-3 small blogs (like the aforementioned wallpaperfx) where it downloads all the pictures, at least from my browsing manually through all pages and map everything. There is a bug report already (#78) where someone mentioned that the download is incomplete, but without a good description, thus I couldn't reproduce the error. Since I don't tumblr myself and randomly checking blogs is a waste of time, I've never tried to fix that.

Do you have a blog where the download is complete? Is that the razrek and do you mind if I crawl through it? Maybe I can find an issue. The problem with tumblr is that there is no simple photo post, but photos posts, photo set posts, photos embedded into other posts, external linked photos, and getting everything right is hard and/or might be impossible.

**Comment by johanneszab** [comment] 2017-11-17 08:52
It should be better now. The pagination (i.e. going to the next webpage) had additionally to the page number also a unix time stamp and thus if you liked a lot of posts in a small time span the page number alone wasn't sufficient for some reason.

The duplicate calculation is still broken since we don't parse the website into a html document and go by the xpath/selectors but just RegEx the whole page as a single string for images and videos. If the same photo is linked twice like in a photo set for the cover picture of the set, the same single photo is actually counted twice.

The next improvement would be to parse the document into a html structure using something like [HTML Agility Pack](http://html-agility-pack.net/) and then act like a browser. Initially I thought it wouldn't work anyways without java script, but the current TumblThree code already contains everything to handle the real web pages. Additionally, parsing the web pages would have benefits like being able to grab text posts or post ids and post time stamps for the photos and videos.

**Comment by johanneszab** [comment] 2017-11-18 12:52
I've one last question. Since the browser that we use for authentication is the actual internet browser and it stores the cookie in it's cache. And from your description, the authentication also worked on your first system. But then TumblThree couldn't use the cookie.

So, any chance you've installed a different set of "security software" like Norton something, that might block accessing the internet explorer data for privacy/security reasons from third-party software?

**Comment by alko1234** [comment] 2017-11-18 14:51
Actually i haven't got any security software, but like u said I tried to my old account on windows clear IE cache, cookies and all of this, and... it works !

**Closed** 2017-11-20 06:42 UTC
