### ISSUE TITLE
Possible implementations and improvements

### ISSUE THREAD

**Issue by DonaldTsang** [johanneszab/TumblThree#254] opened 2018-07-13 15:20 UTC
1. Does TumblThree have an API for interacting with other software? It would be great if TumblThree has API for Python to work with Hydrus (See HydrusNetwork), or at the very least a CLI that works on Linux.
2. Could TumblThree be remade to use Qt/Wx instead of .NET? That would off-load some of the frustration of needing the .NET framework in order to run. I would recommend PyQt (or WxPy to be compatible with Hydrus).

* Main repo: https://github.com/hydrusnetwork/hydrus
* Community: https://github.com/CuddleBear92/Hydrus-Presets-and-Scripts

**Comment by johanneszab** [comment] 2018-07-14 05:40
Duplicate of #176 and #159.

**Closed by johanneszab** 2018-07-14 05:40 UTC
