### ISSUE TITLE
TFA detected when I never activated it

### ISSUE THREAD

**Issue by caterfree10** [johanneszab/TumblThree#307] opened 2018-12-05 03:26 UTC
So I'm trying to log into my tumblr account because I just learned that my blog at my public desktop url is not showing the same posts that my dashboard or mobile app do and I want to make sure it saves all the things. However, when I try to log in, it asks for Two Factor Authorization (TFA) despite my never having activated it on my tumblr account. What is going on and how can I fix this so I can get my blogs backed up?

![image](https://user-images.githubusercontent.com/45614527/49488133-6a857b80-f813-11e8-809a-e52c2660b76b.png)

**Comment by stillwaterspony** [comment] 2018-12-05 04:42
Heyo, I just ran into the same issue. I think it might have to do with tumblr randomly changing its login process whenever you try and login?

Long story short, using this release let me manually login and solved the issue: https://github.com/johanneszab/TumblThree/releases/tag/v1.0.8.51

**Comment by johanneszab** [comment] 2018-12-05 06:32
IMHO, this will happen if Tumblr asks you for a Google catpcha during the login process -- or less likely, if you've wrongly entered your credentials. Note, that you'll need to enter the **email address** used to register at Tumblr, and your **password**. Not your username.

I think what should circumvent this issue (the captcha) is to re-connect to your ISP (via your router/etc). Tumblr will ask you to fill out the captcha after two failed login tries. Maybe you've got unlucky and a spammer IP from your ISP. After getting a new, "fresh" IP from your ISP, I'd retry to login in TumblThree.

If all this doesn't help, you can also use [the previous release](https://github.com/johanneszab/TumblThree/releases/tag/v1.0.8.51) that still uses the Internet Explorer for logging in. However, it will not contain all the changes made after this release (see the [release page](https://github.com/johanneszab/TumblThree/releases) for more).

**Comment by caterfree10** [comment] 2018-12-06 01:41
Well apparently, whatever issue I was having last night seems to have cleared up because I logged in just fine this evening. At any rate, here's hoping the responses in this thread help others who encounter the same problem I did. o7

**Comment by FullMetalFist** [comment] 2018-12-06 16:12
I was asked to enter the TFA when the blog would redirect (happyblog.tumblr.com -> www.tumblr.com/dashboard/blog/happyblog). Then it wouldn't download

**Comment by FullMetalFist** [comment] 2018-12-06 19:07
Apologies!
I had successfully downloaded 3 other blogs, so authentication isn't an issue. Also tried earlier versions which have been posted above & there would be no download if the blog redirects

**Comment by firehawk12** [comment] 2018-12-12 01:01
A bit off topic but Is TFA supported?  I tried entering my generated code and it wouldn't log in.

**Comment by johanneszab** [comment] 2018-12-12 03:44
@firehawk12:
Yes, it's possible.

**Comment by johanneszab** [comment] 2018-12-13 17:19
You can try to use my [Cookies.json](https://www.jzab.de/files/Cookies.json) file for download hidden blogs and Tumblr likes.

This files need to be copied to `%LOCALAPPDATA%\TumblThree\Settings\` while TumblThree is closed! Thus, for a user named xyz, the correct path is: `C:\Users\xyz\AppData\Local\TumblThree\Settings`.

**Comment by johanneszab** [comment] 2018-12-25 08:48
Duplicate of #259.

**Closed by johanneszab** 2018-12-25 08:48 UTC
Labels: question
