### ISSUE TITLE
[Feature Request] Rename file by post name

### ISSUE THREAD

**Issue by hgdagon** [johanneszab/TumblThree#126] opened 2017-08-24 22:57 UTC
Missing this feature so much. Requesting for next release.

**Comment by johanneszab** [comment] 2017-08-25 08:15
Possible duplicate of #119.

**Closed** 2017-08-25 09:13 UTC

**Comment by Taranchuk** [comment] 2017-08-25 11:27
@hgdagon I understand that you are talking about renaming files, using the post caption and possibly also tags? If so, then answer yes and I will write how to do it on your own. For a long time I have renamed files, adding post caption and tags to the file names, so I can write the instructions for you.

**Comment by johanneszab** [comment] 2017-08-25 15:49
Can you post/attach them here? Maybe someone else is interested in it too.

**Comment by Taranchuk** [comment] 2017-08-25 20:42
@hgdagon, well, then here's my instruction. It looks creepy long, but it's because I tried to describe each step so that the beginners could figure it out. The operation itself takes 5 to 10 minutes, so it's not difficult.
First, you need image metadata, TumblThree can download them, you need to check the function of downloading image metadata in the details view and start downloading. Image metadata have everything you need to rename files: file-name, post captions and tags. You need a lot of regular expressions to change the metadata file to a file-list for renaming using a program that can rename files by a file-list (For this you will need Total Commander or another file manager with the function of renaming files by file-list). You need any text editor with the sort function (Personally, I use Notepad++). Also you need a powerful text batch processing tool to quickly process big text files. Use the PowerGrep. I have a saved action file to this program with all the necessary regular expressions, so you can immediately convert the image metadata into a file-list for renaming. Here this file (zipped because GitHub does not accept the format pga)
[rename regex list.zip](https://github.com/johanneszab/TumblThree/files/1252943/rename.regex.list.zip)
If you do not have a PowerGrep or want to use another text editor, then just open this file with plain notepad and copy the necessary regular expressions into the search and replace fields in the text editor and run replace operations. Use it, nothing complicated here. 
Also, you should know that I've added a lot of regular expressions based on my needs. If you do not need something, for example, you do not need to see the names of rebloged blogs and the following text " - reblog" after them in the file name, then remove the corresponding regular expressions. Also there is a regex that limits the length of the lines (somewhere around 200-210 characters) so that there is no error when the full path of the file is more than 259 characters long, if you need more, then edit the corresponding regular expressions. Another thing is, personally I use the function of downloading files with a specific size (in my case it's 1280), but in the image metadata file the filenames are represented with _540, _400, _250. In this case, there is one in the list of regular expressions that replaces them all with _1280. If you do not need this, remove this regex. And if you use this function, but with a raw size, then add |_1280 to the end of the regex in the find field and replace _1280 with a _raw in the replace field. In general, look at the regular expressions and edit them if you see that they give you not what you need. 
To use the "rename regex list.pga" file, you need to open the Powergrep and find the button "Open Actions" and open this file. Next, you only need to select the image metadata file in the file selector and run the replace button. After you get the converted file-list, what's left from the image metadata file. You need to clear it from possible duplicate filenames that have the same basic names (tumblr_something1_1280.jpg). There is a suitable regex (find ^(\S++).*\K(?:\R\1(?:\h.*|$))+ replace nothing), but first you need to replace . (dot) before extensions by a space and . ( .) and also you need to sort the file-list alphabetically, then apply this regex, then you can delete the space before the dot. Then you need to somehow make so that the file-list matches the files in your folder. Here's the problem: in the folder there may be superfluous files or there may be some missing files that could not be downloaded and then in this case in the folder and in the file-list there will be a different number of items. It is necessary to bring them to the same number. It is easier to achieve this if you copy the file-list and past it to another window of the text editor, then you need to form the basic names without post captions, tags and another text. To do this, use the regex (find ^(\S+).*(\.\w\w\w) replace \1\2). If you did everything correctly, you will get the basic filenames, such as in the folder with the files (example tumblr_msrjjq20nP1rhzc8ao1_1280.jpg). Save this file with the base filenames. If you have the Total Commander, go to folder where the downloaded files are located and load the selection from the file with these basic filenames. Compare the number of selected files with the number of lines in the file-list. If the number is the same, then you can proceed to the next stage. If the number is not the same, then you need to do something about it to bring them to the same value. Next, you need to bring the files in the folder and the filenames in the file-list to the same sorting. It is easier to achieve if you sort both files in the Total Commander and the filenames in the file-list alphabetically. However, in Total Commander and your text editor there can be different sorting methods, then this is a problem. If so, then use only sorting method in your text editor. If you already have a sorted file-list, then open the Total Commander and copy the full path of all your selected files (if you have not forgotten, you should have selected files with the basic names of your file-list). Paste the copied full path of selected files into another window of text editor. Then use this regex (find ^(.*\\)(.*) replace \2 ====== \1), sort the text by the same sorting method and use another regex (find (.*) ====== (.*) replace \2\1). Save the text in a file with encoding UTF-8 BOM and open Total Commander, disable sorting mode (ctrl+f7), open the search box and in the field "Search in" write @ and the path to this file (example @C:\path\filenames.txt) and run the search. If you did everything correctly, you will get a list of files exactly as in the file with the base names. You need to select all the files in the window and open the Multi Rename Tool (ctrl+M), on the right there should be a button under ?, click on it, then there should be a button "Edit names", click on it. A text editor window appears with filenames from the Multi Rename Tool. Erase everything and copy everything from the file-list with new filenames and paste it into the file from Multi Rename Tool and save the file. Go to Total Commander, click "OK" on the window, on the right there should be a column with the new renamed files. Carefully check that the base names in the left and right column match. If all match, then start renaming. You have renamed files, but that's not all. If you have photosets, you will notice that only one file from them has been renamed. This is not an error, the fact is that the image metadata store information about only one file from the photosets, so only one file has been renamed, and the rest do not. To rename the rest files from photosets, you need a script. Personally, I use this script for the Total Commander (http://forum.wincmd.ru/viewpost.php?p=121896). To use this, just copy the code of script to a text file with the VBS extension, then put this file on the toolbar Total Commander, go to the script properties and clear the start path, then go to the folder with the files that you need to rename and click the script button and then you need to wait a while for the script to do its work. As the work will be done, then the pop-up window with Russian text will appear and it will mean that everything is already completed, you have all the files renamed. This is the end of the instructions, I tried to write as clearly as possible. One thing: I do not fully speak English, I only study it, so mistakes in the text are possible. If that was not clear, ask. Good luck to you!

**Comment by Taranchuk** [comment] 2017-08-25 21:01
@johanneszab сould you give a link to this instruction somewhere on the page below (https://github.com/johanneszab/TumblThree)? I'm not sure that anyone who wants to rename files by adding post captions and tags to the filenames will see this instruction in a closed topic.

**Comment by hgdagon** [comment] 2017-08-25 22:36
@Taranchuk Good enough for me. Sometimes I download just generic photos, so the filename really doesn't matter, bc I'm gonna rename them manually. But, other I download something very specific, or I download in Bulk (e.g. Web Comic), so I need the files already categorized, since I still have work to do after correcting those files, and then simply bc it's tedious to compare every single comic strip to the Tumblr post for manual renaming. I'll go ahead and try this out, although I'd really prefer for TumblThree to do this automatically, but this is a working solution too.
