### ISSUE TITLE
Option to Ignore Reblogs?

### ISSUE THREAD

**Issue by TheGoodCook** [johanneszab/TumblThree#80] opened 2017-05-19 20:19 UTC
Hello, I am new here but I am trying to download a whole list of original art blogs. However, some of these art blogs contain thousands of reblogs that are also downloaded which increases download times and space used on my PC. Is there an option to ignore reblogs and to only download original posts?

**Comment by johanneszab** [comment] 2017-05-20 06:11
Duplicate of #8.

**Comment by johanneszab** [comment] 2017-05-20 06:11
I'll add that later today. I've already checked the data, shouldn't be more than a few lines of code.

**Comment by TheGoodCook** [comment] 2017-05-20 06:47
Man, thank you so much, some blogs have like 30000 plus reblogs with a few hundred original posts. This will help trim that down and save so much time.

**Closed** 2017-05-20 12:59 UTC
Labels: enhancement
