### ISSUE TITLE
[RfE] Authentication: Show authentication status, current account, and add log-out option

### ISSUE THREAD

**Issue by AriinPHD** [johanneszab/TumblThree#213] opened 2018-02-26 12:27 UTC
### -- Versions tested --
> TumblThree [[v1.0.8.41](https://github.com/johanneszab/TumblThree/releases/tag/v1.0.8.41/)]
> TumblThree [[v1.0.8.39](https://github.com/johanneszab/TumblThree/releases/tag/v1.0.8.39/)]

### -- OS-edition used --
> Windows 10 Pro [v1709] [b16299.248]

### -- Request for Enhancement (RfE) --
Suggestion a few enhancements surrounding "Authentication" and its behavior.

- `Show general authentication status`
   - Currently it's not possible to see if one is authenticated or not. By clicking on the **Settings > Authenticate** button, the **AuthenticateView** window simply opens and automatically closes itself moments later. This behavior can lead to speculation, uncertainty and raise questions such as: _"Did the program crash?", "Did I do something wrong?", "Am I already logged in?", "Am I banned?"_
**By adding an indicator, a display, or clearer logging, indicating a form of **"authentication status"** this problem would be solved.**
- `Show the currently authenticated account (username)`
   - Displaying the currently authenticated user somewhere within TumblThree, and perhaps some visual status-indicators, would possibly help rid any confusion of whether or not a user is logged in and with which account. It could also serve to display any account-related issues, if the service provided API permits such information gathering. Just a bunch of examples:
        - Black lamp/username = Logged-out / Not logged in / Not authenticated
        - Green lamp/username = Logged-in / Authenticated & Account status is good; no throttling or limiting
        - Orange lamp/username = Logged-in / Authenticated & Account status not good; being throttled or download-limited by the service
        - Red lamp/username = Logged-in / Authenticated & Account status bad; banned either temporarily or permanently
- `Allow users to swap accounts (log-out & log-in)`
   - I can't find a log-out option so I'm assuming that once you're logged in once you are actually stuck permanently with that account within TumblThree. This could turn out to not be a problem (ever) but most likely a user would eventually get their account banned by the service due to either high-traffic or just unwanted content. Please allow users to log out and change user, which would solve this issue (and would also let users change accounts that get frozen during settings-testing (download limits etc).

Thanks for a great and beautiful app, @johanneszab :heart:

**Comment by johanneszab** [comment] 2018-02-26 14:26
I see the point.

Just so that you know, you can remove the authentication by deleting the Internet Explorer cookies. Internet Explorer -> Settings Wheel -> Internet Options -> Browsing History -> Delete -> Cookies and website data.

And of course, as you've already noticed, if the window closes immediately, that's because you're still logged in and hence the authentication is still valid. The window that opens is a internet explorer that's redirected to the Tumblr login page. But if you're still logged in, the explorer will be directly redirected from the login page to your dashboard, and then TumblThree closes the window as it notices that you're still logged in.

**Comment by AriinPHD** [comment] 2018-02-26 14:40
Aha, I see! So you've made it use IE for authentication/cookies. That's actually really clever and probably time-saving. :)

So you don't think we will ever see any of the requests being implemented? I'm sure it'll be a low priority regardless, but I'm curious if you think it will be possible at some point. It would be a great convenience (I didn't even know it was connected to IE until now). :)

**Comment by johanneszab** [comment] 2018-03-02 08:02
> So you don't think we will ever see any of the requests being implemented?

No, I think it's doable and not that much code at all. Basically just read the cookie, and optionally remove it. I just never thought about such an option.

**Comment by AriinPHD** [comment] 2018-03-10 15:17
Ah, I see, hehe. Well then I hope we get to see this feature in the future sometime. Thanks for taking the time to read and respond! :)

**Comment by thornate** [comment] 2018-03-22 07:12
> And of course, as you've already noticed, if the window closes immediately, that's because you're still logged in and hence the authentication is still valid. 

I found that the first time I clicked on the 'Authenticate' button when I was already logged in, it closed immediately as you say. Thinking that was a bug, I clicked on it again and it came up with the login screen again (despite already being logged in), except that in this case when I typed in my email address and clicked the 'Next' button, nothing happened. I have confirmed that I am actually still logged in by closing the window without putting my password in again, then queueing a hidden blog.

**Comment by ErikBrown2** [comment] 2018-04-22 14:54
Would it not be possible to have also a configuration setting that enables the user to select auto log-in at the start of TumblThree? This way the application will ensure that the user is always logged in (if this is preferred by the user)

**Comment by Hrxn** [comment] 2018-05-29 11:01
> Currently it's not possible to see if one is authenticated or not. By clicking on the Settings > Authenticate button, the AuthenticateView window simply opens and automatically closes itself moments later. This behavior can lead to speculation, uncertainty and raise questions such as: "Did the program crash?", "Did I do something wrong?", "Am I already logged in?", "Am I banned?"

Well, can confirm. I observed exactly this behaviour, and this was actually my thought process as well, believing that something went wrong I came here to file an issue..

Okay, still working as expected, so all is good. But this comment here still can be considered a "+1" for this request. 😉

**Closed** 2018-07-05 17:32 UTC
Labels: enhancement
