### ISSUE TITLE
Different Themes

### ISSUE THREAD

**Issue by kingbode** [johanneszab/TumblThree#127] opened 2017-08-25 15:18 UTC
I appreciate if you could add different themes with darker color for the user interface

**Comment by johanneszab** [comment] 2017-08-25 15:31
Duplicate of #34.

**Comment by johanneszab** [comment] 2017-08-25 15:40
I've actually tried this once already, but it was way to much work for me at that time. Especially since there were/are more important things to do, like bugfixes, code refactoring or more features in order to have a bit more advanced/distinguished crawler/downloader compared to all the other ones out there.

That's probably why most people either use:
* [MahApps Metro toolkit](https://github.com/MahApps/MahApps.Metro) or
* [Material Design In XAML Toolkit](http://materialdesigninxaml.net/)

They both look pretty and using them is as simple as adding a few lines code. But then it looks like all the other apps again ;). I think the new TumblRipper is also using it and selling it as "big new feature" for basically no own work.

**Comment by johanneszab** [comment] 2017-08-25 15:41
If you want, you can play around with it. I'll probably still find enough other playgrounds to sink time into.

**Closed** 2017-08-27 09:13 UTC
