### ISSUE TITLE
"raw" filesize?

### ISSUE THREAD

**Issue by mfriendc** [johanneszab/TumblThree#93] opened 2017-06-21 00:34 UTC
I heard (and it seems to be true) that "_raw.***" is the actual largest size for a tumblr image

do you think you could add it as an option to the "max filesize to download" list?

http://puu.sh/wpWYA/78917e27b1.png

**Comment by johanneszab** [comment] 2017-06-21 04:58
Duplicate of #92.

**Comment by johanneszab** [comment] 2017-06-21 04:59
You could at least have looked at the last release, the last commit, the last issue before posting this.

**Closed by johanneszab** 2017-06-21 04:59 UTC
Labels: duplicate, enhancement

**Comment by mfriendc** [comment] 2017-06-23 07:14
sorry about that, I was under the assumption that it was as much new information to everyone else as it was to me since I'd only heard of it that day

**Comment by johanneszab** [comment] 2017-06-23 07:23
Ahh,.. no problem. Just forget it. My reaction was kinda harsh. I'm glad that you leaked out the information to this project. I'm no way into actively tumblr'ing or on any related site, so thanks for the info!
