### ISSUE TITLE
_files_files.tumblr

### ISSUE THREAD

**Issue by blezinski** [johanneszab/TumblThree#76] opened 2017-05-02 21:17 UTC
changed from .31 to .42 and it created a new file for each blog, so now i have
blog.tumblr
blog_files.tumblr
and blog_files_files.tumblr
i dunno what's going on but whenever i delete it it just comes back

**Comment by johanneszab** [comment] 2017-05-03 05:34
Duplicate of #64.

**Comment by johanneszab** [comment] 2017-05-03 05:37
Please check [my answer in this issue](https://github.com/johanneszab/TumblThree/issues/64#issuecomment-294370372).

There was a bug in the file handling which is supposed to be more robust now and it's not neccessary to touch it again.
You can either use a editor like Notepad++ to mass change the Name field in all your _files.tumblr files within a directory or redo the conversion using the now fixed v1.0.4.31 version.

**Closed by johanneszab** 2017-05-03 05:37 UTC
Labels: bug, duplicate
