### ISSUE TITLE
No Application?

### ISSUE THREAD

**Issue by PonyGirl6763** [johanneszab/TumblThree#136] opened 2017-09-03 23:27 UTC
I'm using Winrar on a Windows 10 computer to extract the file once I download it. After that, I go to look for a Tumblthree.exe file and there isn't one there. I've looked through all the files and deleted the all the unzipped files and folders to redownload. It's just not showing up anywhere. I don't know if I'm looking for the wrong thing or what is going on?

**Comment by johanneszab** [comment] 2017-09-04 05:14
https://github.com/johanneszab/TumblThree/releases/latest

**Comment by johanneszab** [comment] 2017-09-04 05:15
Duplicate of #120.

**Closed by johanneszab** 2017-09-04 05:15 UTC
